version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "$PWD/video:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8000:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  my_project:
    build: .
    links:
      - selenoid
    depends_on:
      - selenoid
    environment:
      - MODULE=web.xml